apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: busyargo
  name: busyargo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busyargo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busyargo
    spec:
      containers:
      - image: championsleague12/busybox
        name: busybox
        resources: {}
status: {}
